//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImdbQuiz
{
    using System;
    using System.Collections.Generic;
    
    public partial class top250imdb
    {
        public int Id { get; set; }
        public Nullable<int> Votes { get; set; }
        public Nullable<decimal> Rank { get; set; }
        public string Title { get; set; }
        public string Year { get; set; }
    }
}
